name: nutriclock_app
description: An application to help monitorize nutritional plans

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.12.2
  shared_preferences: ^0.5.6+1
  splashscreen: 1.2.0
  image_picker: ^0.6.7+11
  intl: 0.16.1
  flutter_typeahead: ^1.8.8
  percent_indicator: ^2.1.8
  syncfusion_flutter_datepicker: ^18.3.50-beta
  multiselect_formfield: ^0.1.5
  syncfusion_flutter_charts: ^18.3.52
  loading: ^1.0.2
  badges: ^1.1.6
  web_socket_channel: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/images/bg_login.png
    - assets/images/nutri.png
    - assets/images/logo.png
    - assets/images/logo_horizontal.png
    - assets/images/header.png
    - assets/images/tips.png
    - assets/images/stats.png
    - assets/images/pillow.png
    - assets/images/bg_drawer.jpg
    - assets/images/bg_home.jpg
    - assets/images/bg_sleep.jpg
    - assets/sleep/sleep.png
    - assets/sleep/stats.png
    - assets/sleep/tip.png
    - assets/images/header_chat.png
    - assets/images/bg_chat.jpg
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Neucha
      fonts:
        - asset: fonts/Neucha-Regular.ttf
    - family: PatrickHand
      fonts:
        - asset: fonts/PatrickHand-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Medium.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
